### ISSUE TITLE
Bug: Registration fails over https

### ISSUE THREAD

**Issue by gorrdy** [honzanoll/btcpayserver-stream#2]
Hi,

I managed to get to work the Docker container and generated the certificates myself.

Then I struggled with registration and discovered it was the secured connection.

Over http it was good (not much secure though - I run it in cloud).

Nothing in docker logs, nor any other info other than "Something went wrong" alert.

**Comment by gorrdy** [comment]
Also login is doing nothing. 

Only thing I found in the logs is 

`portal_1  | 2023-04-11 11:42:44.9697|ERROR|Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery|An exception was thrown while deserializing the token.
portal_1  | 2023-04-11 11:42:56.7220|ERROR|Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery|An exception was thrown while deserializing the token.`

**Comment by honzanoll** [comment]
Hi,
the application is able to run in HTTP mode only.

If you need HTTPS, you need to use a reverse proxy.

**Comment by gorrdy** [comment]
I use reverse proxy ofc but this is not the problem I think.

Although I managed to get it work by using the docker-compose.yml, cloning the repo and adding these, then running the docker-compose build. 

```
services:
  portal:
    image: "honzanoll/btcpayserver-stream:1.0.2"
    environment:
      - GlobalSettings:Infrastructure:FEUrl=https://donate.mydomain.com
      - StreamlabsSettings:ClientId=6...........3
      - StreamlabsSettings:ClientSecret=N...............N
    volumes:
      - /home/user/btcpayserver-stream/Storage:/Storage
      - /home/user/btcpayserver-stream/Database:/Database
    ports:
        - "5555:5000"
    build:
        context:  /home/user/btcpayserver-stream/src/
        dockerfile: Dockerfile
    restart: always
```

Then the build and up

`sudo docker-compose build;`
`sudo docker-compose up -d;`
